language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - npm run bundle
  - npm run build
deploy:
  - provider: surge
    project: ./
    domain: vue-highlight-text.surge.sh
    skip-cleanup: true
    on:
      branch: master
  - provider: npm
    email: ${EMAIL}
    api_key: ${AUTH_TOKEN}
    skip_cleanup: true
    on:
      branch: master